source 'http://rubygems.org'

if RUBY_VERSION < '1.9'
  gem 'ruby-debug'
else
  gem 'ruby-debug19'
end

gem 'database_cleaner'


gem "spreadsheet", "~> 0.6.5.9"
gem 'to_xls'


gem "pdfkit"
gem "wkhtmltopdf-binary"



gemspec
