source 'http://rubygems.org'

if RUBY_VERSION < '1.9'
  gem 'ruby-debug'
else
  gem 'ruby-debug19'
end


gem "spreadsheet", "~> 0.6.5.9"
gem 'to_xls'


gem "pdfkit"
gem "wkhtmltopdf-binary"

group :test do
  #gem 'turn'
  gem 'database_cleaner'
end


gemspec
