mode : "exact"
theme : "advanced"
language : "<%= I18n.locale.to_s.split('-')[0].downcase %>"
skin : "o2k7"
width : "594"
plugins : "safari,style,layer,table,advhr,advimage,inlinepopups,insertdatetime,preview,media,searchreplace,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template"

# Theme options
theme_advanced_buttons1 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,fullscreen,|,charmap,media,advhr,|,visualchars,blockquote"
theme_advanced_buttons2 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,sub,sup,|,bullist,numlist,|,outdent,indent,blockquote,|,"
theme_advanced_buttons3 : "styleselect,formatselect,fontselect,fontsizeselect,|,forecolor,backcolor"
theme_advanced_buttons4 : "tablecontrols,|,hr,removeformat,visualaid"
theme_advanced_toolbar_location : "top"
theme_advanced_toolbar_align : "left"
theme_advanced_statusbar_location : "top"
theme_advanced_resizing : false


